apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-config
data:
  DATABASE_URL: "postgresql://postgres:password@postgres:5432/observability_db"
  MONGODB_URI: "mongodb://mongodb:27017/observability_logs"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  KAFKA_BROKER: "kafka:29092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  PORT: "3000"
  NODE_ENV: "production"
  JWT_EXPIRES_IN: "7d"